version: '3.2'
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - "./volumes:/var/lib/postgresql/data"

  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      DB_HOSTNAME: "postgres"
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    command:
      - ./run.sh
